### ISSUE TITLE
Incorrect field type defined in ResponseNetworkDeviceGetNetworkDeviceByNameNetworkDeviceTrustsecsettings

### ISSUE THREAD

**Issue by r00tkitcdrive** [CiscoISE/ciscoise-go-sdk#32]
**Prerequisites**
* [YES] Have you tested the operation in the API directly?
* [YES] Do you have the latest SDK version?

**Describe the bug**
struct field"ResponseNetworkDeviceGetNetworkDeviceByNameNetworkDeviceTrustsecsettings.PushIDSupport" is defined as a `*bool` type however, ISE response is of  `string` type.  

performing a call using to either
func (s *NetworkDeviceService) GetNetworkDeviceByName(name string)
or 
func (s *NetworkDeviceService) GetNetworkDeviceByID(id string)

Throws the same error:::
error: json: cannot unmarshal string into Go struct field ResponseNetworkDeviceGetNetworkDeviceByNameNetworkDeviceTrustsecsettings.NetworkDevice.trustsecsettings.pushIdSupport of type bool

**Expected behavior**
Changing field PushIDSupport in the struct fixes the issues and stop this crash from happening
type ResponseNetworkDeviceGetNetworkDeviceByNameNetworkDeviceTrustsecsettings struct {
       PushIDSupport   string  `json:"pushIdSupport,omitempty"`
}

**Screenshots**
![image](https://github.com/CiscoISE/ciscoise-go-sdk/assets/33535006/172f422f-be56-403d-90b0-263838202dd8)
![image](https://github.com/CiscoISE/ciscoise-go-sdk/assets/33535006/2b1bc3ea-4810-4408-a27e-cc1119fe6bcb)
![image](https://github.com/CiscoISE/ciscoise-go-sdk/assets/33535006/94bb5ca9-faf6-409a-8cc4-93e950b2d77b)

**Environment (please complete the following information):**
* ISE version and patch: 3.1.0.518 Path 1,3,4,5,6
* Go version: 1.21.0
* SDK version: 1.1.22
* OS version: ubuntu 20.04

**Verify compatibility**
* https://github.com/CiscoISE/ciscoise-go-sdk/tree/main#compatibility-matrix

**Additional context**

**Comment by bvargasre** [comment]
Fixed in v1.3.3
